{% set python_min = "3.10" %}
{% set name = "txl-widgets" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_widgets-{{ version }}.tar.gz
  sha256: 65a5cf8b16de9e6e5d1f1d58f63df23bb0500ec75efe833cb4242d8670c1711c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.1
    - ypywidgets >=0.9.4,<0.10.0
    - ypywidgets-textual >=0.5.1,<0.6.0
    - pycrdt >=0.10.9,<0.13.0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - txl_widgets

about:
  home: https://codeberg.org/davidbrochart/jpterm/src/branch/main/plugins/widgets
  summary: TXL plugin for widgets
  dev_url: https://codeberg.org/davidbrochart/jpterm/src/branch/main/plugins/widgets
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
