{% set name = "txl-widgets" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_widgets-{{ version }}.tar.gz
  sha256: cb5b2531fcfbcda34d78b42ac1a0c8ab5d726ea01bf88ad383dcb2a1e0507d12

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - ypywidgets >=0.7.0,<0.8.0
    - ypywidgets-textual >=0.4.0,<0.5.0
    - pycrdt >=0.8.11,<0.9.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_widgets

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/widgets
  summary: TXL plugin for widgets
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/widgets
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
